version: '2.2'

services:
  openhab:
    image: "openhab/openhab:2.3.0-amd64-debian"
    container_name: "synology_openhab_openhab"
    restart: always
    network_mode: host
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/TZ:/etc/timezone:ro"
      #- "./openhab_addons:/openhab/addons"
      - "./openhab_conf:/openhab/conf"
      #- "./openhab_userdata:/openhab/userdata"
      - "openhab_userdata_log:/openhab/userdata/logs"
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"
  frontail:
    image: welteki/frontail-openhab
    container_name: synology_openhab_frontail
    restart: always
    network_mode: host
    ports:
      - "9001:9001"
    volumes:
      - openhab_userdata_log:/openhab/userdata/logs
volumes:
  openhab_userdata_log: